# default config
# -----------------------------------------------------------------------------
# default config values for sampling from models

init_from: 'resume'
out_dir: 'out'
start: "\n"
num_samples: 10 # number of samples to draw
max_new_tokens: 500 # number of tokens generated in each sample
temperature: 0.8 # 1.0 = no change, < 1.0 = less random, > 1.0 = more random, in predictions
top_k: 200 # retain only the top_k most likely tokens, clamp others to have 0 probability
seed: 1337
device: 'cuda'
compile: false